# Site settings
title: Physics of life 2023
email: mark.wallace@kcl.ac.uk
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://physicsoflife.net" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
